---
title: Class Diagram
---
classDiagram
    class Command {
        +Result execute()
    }

    class Repository{
        +bool create()
        +T findOne()
        +Stream findAll()
        +Stream findMany()
        +bool update()
        +bool deleteOne()
        +int deleteMany()
    }

    class InMemoryRepository {
    }

    class DataEntity {
        +getTableHead()
        +getTableRow()
        +gettersAndSetters()
    }

    class QueryBuilder{
        +Map inventoryQuery()
        +Map supplierQuery()
        +Map customerOrderQuery()
        +Map supplierPurchaseQuery()
        -Map filterQuery()
    }

    class CommandParser {
        +getCommand()
    }

    class InputParser{
        +String parseString()
        +Int parseInt()
        +Double parseDouble()
    }

    class ValidatedInputParser{
        +String parseString()
        +Int parseQuantity()
        +Double parseAmount()
    }

    class Printer{
        +void info()
        +void error()
        +void success()
        +void warning()
        +void alert()
        +void logo()
        +void printTable()
        -void printTableRow()
        +public void setOutputStream()
    }

    class CommandRegistry {
        +Result processCommand()
    }

    Repository --|> InMemoryRepository: Implements, T = DataEntity
    InputParser --|> ValidatedInputParser: Extends
    ValidatedInputParser --> QueryBuilder
    ValidatedInputParser --> Command
    Command --> Printer
    QueryBuilder --> Command: Creates hashmaps
    InMemoryRepository <--> Command: Command sends querys/entities,\nReceives Entities
    DataEntity .. InMemoryRepository: Stores
    DataEntity .. Command: Uses
    CommandRegistry *-- Command: Contains Map of Commands
    CommandParser --|> CommandRegistry: Uses to select command
    note "NOTE: Implementations of Command\n may use multiple repositories as needed."